# Generated by Django 5.1 on 2024-09-01 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
                ('period', models.IntegerField(blank=True, default=0)),
                ('archive', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events')),
            ],
        ),
    ]
